export const QUIZ_QUESTIONS = [
  {
    id: 1,
    question: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Central Program Unit",
      "Central Peripheral Unit",
    ],
    correctAnswer: "Central Processing Unit",
  },
  {
    id: 2,
    question:
      "Which data structure follows Last In First Out (LIFO) principle?",
    options: ["Queue", "Array", "Stack", "Linked List"],
    correctAnswer: "Stack",
  },
  {
    id: 3,
    question: "What is the time complexity of Quick Sort in average case?",
    options: ["O(n)", "O(n^2)", "O(log n)", "O(n log n)"],
    correctAnswer: "O(n log n)",
  },
  {
    id: 4,
    question: "Which protocol is used for sending email?",
    options: ["HTTP", "FTP", "SMTP", "TCP"],
    correctAnswer: "SMTP",
  },
  {
    id: 5,
    question: "What does HTML stand for?",
    options: [
      "Hyper Text Markup Language",
      "High Tech Modern Language",
      "Hyper Transfer Markup Language",
      "Hyperlink and Text Markup Language",
    ],
    correctAnswer: "Hyper Text Markup Language",
  },
  {
    id: 6,
    question: "Which of these is NOT a programming paradigm?",
    options: ["Functional", "Object-Oriented", "Procedural", "Logarithmic"],
    correctAnswer: "Logarithmic",
  },
  {
    id: 7,
    question: "What is the primary purpose of an operating system?",
    options: [
      "Run applications",
      "Manage computer hardware and software resources",
      "Create websites",
      "Generate reports",
    ],
    correctAnswer: "Manage computer hardware and software resources",
  },
  {
    id: 8,
    question: "What does API stand for?",
    options: [
      "Advanced Programming Interface",
      "Application Programming Interface",
      "Automated Program Interaction",
      "Application Process Integration",
    ],
    correctAnswer: "Application Programming Interface",
  },
  {
    id: 9,
    question: "Which programming language is known for machine learning?",
    options: ["Java", "C++", "Python", "Ruby"],
    correctAnswer: "Python",
  },
  {
    id: 10,
    question: "What is a binary search tree?",
    options: [
      "A tree where each node has at most two children",
      "A linear data structure",
      "A sorting algorithm",
      "A networking protocol",
    ],
    correctAnswer: "A tree where each node has at most two children",
  },
  {
    id: 11,
    question: "What does DNS stand for?",
    options: [
      "Digital Network System",
      "Domain Name System",
      "Dynamic Network Service",
      "Distributed Network Setup",
    ],
    correctAnswer: "Domain Name System",
  },
  {
    id: 12,
    question: "Which of these is a type of cloud computing service?",
    options: ["SAS", "PAS", "IAS", "SaaS"],
    correctAnswer: "SaaS",
  },
  {
    id: 13,
    question: "What is Big O notation used for?",
    options: [
      "Designing websites",
      "Measuring algorithm efficiency",
      "Creating databases",
      "Network security",
    ],
    correctAnswer: "Measuring algorithm efficiency",
  },
  {
    id: 14,
    question: "What does URL stand for?",
    options: [
      "Universal Reference Link",
      "Uniform Resource Locator",
      "Universal Resource Link",
      "Unified Reference Locator",
    ],
    correctAnswer: "Uniform Resource Locator",
  },
  {
    id: 15,
    question:
      "Which programming concept involves hiding complex implementation details?",
    options: ["Encryption", "Abstraction", "Compilation", "Interpretation"],
    correctAnswer: "Abstraction",
  },
  {
    id: 16,
    question: "What is a firewall?",
    options: [
      "A type of computer hardware",
      "A network security system",
      "A programming technique",
      "A type of software application",
    ],
    correctAnswer: "A network security system",
  },
  {
    id: 17,
    question: "What does SQL primarily used for?",
    options: [
      "System Query Language",
      "Structured Query Language",
      "Standard Query Language",
      "Server Query Language",
    ],
    correctAnswer: "Structured Query Language",
  },
  {
    id: 18,
    question:
      "Which memory management technique reduces external fragmentation?",
    options: ["Paging", "Segmentation", "Swapping", "Caching"],
    correctAnswer: "Paging",
  },
  {
    id: 19,
    question: "What is a deadlock in operating systems?",
    options: [
      "A type of virus",
      "A situation where processes wait indefinitely",
      "A network connection issue",
      "A hardware failure",
    ],
    correctAnswer: "A situation where processes wait indefinitely",
  },
  {
    id: 20,
    question: "What does JSON stand for?",
    options: [
      "JavaScript Object Notation",
      "Java Serialized Object Notation",
      "JavaScript Oriented Networking",
      "Java Standard Object Notation",
    ],
    correctAnswer: "JavaScript Object Notation",
  },
  {
    id: 21,
    question:
      "What is the primary difference between compiler and interpreter?",
    options: [
      "Compilers are faster",
      "Interpreters translate code line by line",
      "Compilers translate entire program at once",
      "Interpreters are used only in web development",
    ],
    correctAnswer: "Compilers translate entire program at once",
  },
  {
    id: 22,
    question: "What does RAM stand for?",
    options: [
      "Random Access Memory",
      "Read Access Memory",
      "Random Allocated Memory",
      "Read Allocated Memory",
    ],
    correctAnswer: "Random Access Memory",
  },
  {
    id: 23,
    question: "Which network topology connects all devices to a central node?",
    options: ["Ring", "Mesh", "Star", "Bus"],
    correctAnswer: "Star",
  },
  {
    id: 24,
    question: "What is version control primarily used for?",
    options: [
      "Controlling computer versions",
      "Managing software development",
      "Tracking code changes",
      "Updating operating systems",
    ],
    correctAnswer: "Tracking code changes",
  },
  {
    id: 25,
    question: "What does HTTPS indicate?",
    options: [
      "High Transfer Protocol Secure",
      "Hyper Text Transfer Protocol Secure",
      "High Text Transfer Protocol Standard",
      "Hyper Transfer Protocol Secure",
    ],
    correctAnswer: "Hyper Text Transfer Protocol Secure",
  },
  {
    id: 26,
    question: "What is a primary function of a router?",
    options: [
      "Store data",
      "Process data",
      "Forward data packets between networks",
      "Generate reports",
    ],
    correctAnswer: "Forward data packets between networks",
  },
  {
    id: 27,
    question: "Which sorting algorithm has the best average time complexity?",
    options: ["Bubble Sort", "Insertion Sort", "Quick Sort", "Selection Sort"],
    correctAnswer: "Quick Sort",
  },
  {
    id: 28,
    question: "What does EOF stand for in programming?",
    options: [
      "End of File",
      "End of Function",
      "External Output Format",
      "Error on File",
    ],
    correctAnswer: "End of File",
  },
  {
    id: 29,
    question: "What is artificial intelligence primarily focused on?",
    options: [
      "Creating human-like robots",
      "Developing intelligent machines",
      "Writing complex algorithms",
      "Designing computer networks",
    ],
    correctAnswer: "Developing intelligent machines",
  },
  {
    id: 30,
    question: "What is a primary characteristic of blockchain technology?",
    options: [
      "Centralized control",
      "Decentralized and transparent",
      "Limited data storage",
      "Single point of failure",
    ],
    correctAnswer: "Decentralized and transparent",
  },
];
